Product.create(name: 'Lean Gr. Beef', description: 'Our 90-10 mixture. There\'s no grease to drain and it\'s ground fresh daily.', category: 'Beef')
Product.create(name: 'Regular Gr. Beef', description: 'Our 80-20 mixture. Makes great hamburgers on the grill. Ground fresh daily.', category: 'Beef')
Product.create(name: 'Ossian Bacon', description: 'Ossian\'s own thick sliced bacon. Great on burgers and blt\'s... What am I talking about, it\'s bacon. It\'s great on everything.', category: 'Pork')
Product.create(name: 'Amish Fryers', description: 'Whole frying chickens raised in the Amish country in Orland, IN. Some of the best poultry ever.', category: 'Poultry')
Product.create(name: 'Regular Brats', description: 'Ken\'s original brat. Throw some on the grill, today.' category: 'Pork/Beef')
Product.create(name: 'Cajun Brats', description: 'Like Ken\'s regular brats, but with a bit of cajun heat.', category: 'Pork/Beef')
Product.create(name: 'Regular O/P Brats', description: 'Our regular brats with chopped green pepper and sweet onions', category: 'Pork/Beef')
Product.create(name: 'Cajun O/P Brats', description: 'Whoa Nelly, watch out! Ken\'s cajun brat packed with green pepper and onions.', category: 'Pork/Beef')
Product.create(name: 'Chuck Roasts', description: 'Add some potatoes and carrots and you\'re in Pot Roast Heaven', category: 'Beef')
Product.create(name: 'Whole NY Strip Loin', description: 'Love steak, but you\'re on a budget, this is the deal for you. Get it cut and packaged to your specifications.', category: 'Beef')
Product.create(name: 'Delmonico Steak', description: 'Otherwise known as a Boneless Ribeye, this tender cut is great for special occassions.', category: 'Beef')
Product.create(name: 'Rib Steak', description: 'Also known as a Bone-in Ribeye, it\'s from the same loin as the Delmonico. Very Tender.', category: 'Beef')
Product.create(name: 'Sirloin Steak', description: 'So good a knight from Sir Arthur\'s table dubbed him \'Sir\'loin, these cuts can be pretty mammoth! Look for marbling for the best flavor.', category: 'Beef')
Product.create(name: 'NY Strip Steak', description: 'As the larger side of a T-Bone, this cut can really hit the spot.', category: 'Beef')
Product.create(name: 'T-Bone Steak', description: 'Take home that bone-in flavor, and throw one on the grill.', category: 'Beef')
Product.create(name: 'Porterhouse Steak', description: 'The Grand-Daddy of \'em all. Delicious NY strip on one side, and mouth-watering filet on the other.', category: 'Beef')
Product.create(name: 'Cube Steak', description: 'Bread and fry to make a great country-fried steak.', category: 'Beef')
Product.create(name: 'Sirloin Roast', description: 'Need a fancy slicing Roast, this is your guy.', category: 'Beef')
Product.create(name: 'Rump Roast', description: 'Need a fancy slicing Roast, this is your guy.', category: 'Beef')
Product.create(name: 'Filet Mignon', description: '<i>The</i> melt in your mouth steak.', category: 'Beef')
Product.create(name: 'Beef Ribs', description: 'These Beef Baby Back Ribs are great for flavoring soups and stews.', category: 'Beef')
Product.create(name: 'Beef Femur Bones', description: 'These make great dog or soup bones.', category: 'Beef')
Product.create(name: 'Ken\'s Beef Jerky', description: 'His own special recipe, this jerky isn\'t dry and brittle, but moist and chewy!', category: 'Beef')
Product.create(name: 'Pork Spare Ribs', description: 'These ribs are great for grilling. Ask Ken to St. Louis cut them--free of charge.', category: 'Pork')
Product.create(name: 'Pork Steak', description: 'A slice of pork shoulder-butt. Great for Barbecueing.', category: 'Pork')
Product.create(name: 'Loin Pork Chops', description: 'These guys are the \'Porterhouse\' of the pork chops.', category: 'Pork')
Product.create(name: 'Thick Pork Chops', description: 'These chops are cut at a manly 1" thick. Great for stuffing.', category: 'Pork')
Product.create(name: 'Rib Pork Chops', description: 'These small and inexpensive chops make feeding a large family easy!', category: 'Pork')
Product.create(name: 'Butterfly Chops', description: 'Our boneless chop, caught by Ken with his giant bug catching net. :)', category: 'Pork')
Product.create(name: 'Pork Baby Back Ribs', description: 'These are plenty meaty and tender. Great for Barbecueing!', category: 'Pork')
Product.create(name: 'Pork Cutlets', description: 'These are like our pork tenders, but without the breading. Great for low carb diets.', category: 'Pork')
Product.create(name: 'Smoked Pork Chops', description: 'These beauties are made under Ossian\'s Hoosier Pride Label, but make no mistake, the flavor is 100% Ossian!', category: 'Pork')
Product.create(name: 'Country Ribs', description: 'Boneless ribs that will make your mouth sing with delight!', category: 'Pork')
Product.create(name: 'Boneless Pork Loin', description: 'A great addition to any family celebration.', category: 'Pork')
Product.create(name: 'Pork Tenders', description: 'Ken\'s take on the pork tenderloin, but meatier.', category: 'Pork')
Product.create(name: 'Chicken Tenders', description: 'These are cubed and breaded right here at Ken\'s, and excellent when pan fried in butter or oil.' category: 'Poultry')
Product.create(name: 'Ossian Bone-in Hams', description: 'Ossian has several kinds of these, so please be specific when you order', category: 'Pork')
Product.create(name: 'Country Sausage', description: 'Ground and mixed on site, this sausage makes a mean sausage, gravy and biscuits', category: 'Pork')
Product.create(name: 'Ken\'s Smoked Sausage', description: 'Ground, cured, and smoked by Ken, this sausage is a real treat.', category: 'Pork/Beef')
Product.create(name: '10# Bag GB', description: 'Family-sized package of hamburger. Bulk pricing available.', category: 'Beef')
Product.create(name: '10# Bag Lean GB', description: 'Family-sized package of lean hamburger. Bulk pricing available.', category: 'Beef')
Product.create(name: 'Chicken Leg Quarters', description: 'Our bone-in chicken staple.', category: 'Poultry')
Product.create(name: 'Chicken Wings', description: 'Usually these can be found in the freezer, 2#/package.', category: 'Poultry')
Product.create(name: 'Boneless Chicken Breasts', description: 'The ever versatile chicken breast.', category: 'Poultry')
Product.create(name: 'Bone-in Chicken Breasts', description: 'In stock on rare occassions, these are great for frying or grilling', category: 'Poultry')
Product.create(name: 'Ken\'s Beer Stick', description: 'Ken\'s own special blend of beef, pork, and spices, then smoked over night to make this great snack-stick.', category: 'Pork/Beef')